### PR TITLE
Add test tools

### PR DESCRIPTION
**Pull request by angelosilvestre**
This PR adds some test tools so we can test LSP methods without having to run the whole app.

I added two simple test just to demonstrate how we can use it. We will be able to use relative paths, so it will be easier to run in anyone's machine.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
cc @suragch @rutvik110

**Comment by matthew-carroll** [comment]
Can you add a test project under the test directory and switch to that before we merge this in?

**Comment by angelosilvestre** [comment]
@matthew-carroll Added a test project. I didn't add the platform folders because I think we won't need them.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Pull request merged**
